# Generated by Django 3.2.16 on 2023-01-14 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64)),
                ('repo_link', models.CharField(max_length=128)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('activate', models.BooleanField(default=True, verbose_name='active')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.project')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
